<a href="https://colab.research.google.com/github/SimmonLEe/THU_PatternRecognition/blob/main/FisherDiscrimate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

导入数据 并且求解两类的类内离差矩阵与类间离差矩阵

In [16]:
import numpy as np
import pandas
import sklearn

In [17]:
from sklearn.datasets import load_breast_cancer

In [21]:
breast_cancer_data = load_breast_cancer()
breast_cancer_data.data.shape

(569, 30)

In [24]:
breast_cancer_data.target.shape

(569,)

In [26]:
data = breast_cancer_data.data
label = breast_cancer_data.target

In [32]:

train_data = data[:400]
test_data = data[400:]
train_label = label[:400]
test_label = label[400:]

In [38]:
# 将数据第一类与第二类选出
class_zero_mask = (train_label == 0)
class_one_mask = (train_label != 0)
CLASS_0 = train_data[class_zero_mask]
CLASS_1 = train_data[class_one_mask]
print("CLASS_0_SHAPE:{}, CLASS_1_SHAPE:{}".format(CLASS_0.shape, CLASS_1.shape))

CLASS_0_SHAPE:(173, 30), CLASS_1_SHAPE:(227, 30)


In [42]:
# 求解协方差矩阵
Covar_0 = np.cov(CLASS_0.T)
Covar_1 = np.cov(CLASS_1.T)

In [46]:
# 求解均值
mean_0 = np.mean(CLASS_0, axis=0)
mean_1 = np.mean(CLASS_1, axis=0)

## fisher 判别分析
## 在空间中寻找一个超平面, 将特征空间中的点投影到该超平面上, 且使得不同类之间尽量分散，同类之间尽量接近
## Q1:如何来描述不同类之间的距离呢，又如何来描述同类之间的距离呢?
### answer:使用协方差矩阵来描述同类数据之间的距离, 使用两个类之间的均值距离来衡量不同类之间的距离,那么我们的目标就是在空间中寻找一个超平面，在数据投影上去之后 使得协方差矩阵小, 而类间矩阵大
minSw maxSb

In [49]:
Sw = Covar_0 +Covar_1
Sb = (mean_0 - mean_1) * (mean_0 - mean_1)

array([2.70755522e+01, 1.80061169e+01, 1.33153658e+03, 2.50466067e+05,
       1.17304885e-04, 4.42030048e-03, 1.22451499e-02, 3.78023862e-03,
       3.53212642e-04, 2.34802497e-10, 9.88305259e-02, 3.23550969e-04,
       5.15065185e+00, 2.41538506e+03, 1.51775073e-07, 1.09682619e-04,
       1.94152755e-04, 2.40404131e-05, 1.14630016e-07, 9.37868688e-08,
       5.96430425e+01, 4.54783783e+01, 2.91719145e+03, 7.26836199e+05,
       4.82266887e-04, 4.02214635e-02, 7.92686476e-02, 1.19367139e-02,
       3.35849719e-03, 1.72994836e-04])

array([0.5, 0.4, 0.4])

array([[ 0.08, -0.04,  0.  ],
       [-0.04,  0.02,  0.  ],
       [ 0.  ,  0.  ,  0.  ]])